updating failure message

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -73,9 +73,7 @@ OSCP-Cluster-Mode:
       SESSION=$(echo $BUILD_IMG_TAG | awk -F ':' '{print $2}')
       sed -i  "/bigip_controller_img/c\    \"bigip_controller_img\": \"${BUILD_IMG_TAG}\"," ~/testenv_symbols/testenv_symbols.json
       cd $HOME/${TEST_DIR} && scripts/run_systests.sh   --project=bigip_ctlr --session=${SESSION}-cluster --include-tags=${INCLUDE_TAGS} --orchestration=openshift --pool-mode=cluster --namespace-mode=${NAMESPACE_MODE} --exclude-tags=${EXCLUDE_TAGS};
-      echo $PATH
-      ifconfig
-      if [ $(cat $HOME/test_results/${SESSION}-cluster/${SESSION}-cluster-sessionresult.json | jq -r '.result') != "pass" ]; then exit 1; fi 
+      if [ $(cat $HOME/test_results/${SESSION}-cluster/${SESSION}-cluster-sessionresult.json | jq -r '.result') != "pass" ]; then echo "Smoke test failed"; exit 1; fi 
 
 OSCP-Nodeport-Mode:
   tags: 
@@ -89,7 +87,7 @@ OSCP-Nodeport-Mode:
       SESSION=$(echo $BUILD_IMG_TAG | awk -F ':' '{print $2}')
       sed -i  "/bigip_controller_img/c\    \"bigip_controller_img\": \"${BUILD_IMG_TAG}\"," ~/testenv_symbols/testenv_symbols.json
       cd $HOME/${TEST_DIR} && scripts/run_systests.sh   --project=bigip_ctlr --session=${SESSION}-nodeport --include-tags=${INCLUDE_TAGS} --orchestration=openshift --pool-mode=nodeport --namespace-mode=${NAMESPACE_MODE} --exclude-tags=${EXCLUDE_TAGS} ;
-      if [ $(cat $HOME/test_results/${SESSION}-cluster/${SESSION}-nodeport-sessionresult.json | jq -r '.result') != "pass" ]; then exit 1; fi 
+      if [ $(cat $HOME/test_results/${SESSION}-cluster/${SESSION}-nodeport-sessionresult.json | jq -r '.result') != "pass" ]; then echo "Smoke test failed"; exit 1; fi 
 
 K8s-Cluster-Mode:
   tags: 
@@ -104,7 +102,7 @@ K8s-Cluster-Mode:
       SESSION=$(echo $BUILD_IMG_TAG | awk -F ':' '{print $2}')
       sed -i  "/bigip_controller_img/c\    \"bigip_controller_img\": \"${BUILD_IMG_TAG}\"," ~/testenv_symbols/testenv_symbols.json
       cd $HOME/${TEST_DIR} && scripts/run_systests.sh   --project=bigip_ctlr --session=${SESSION}-cluster --include-tags=${INCLUDE_TAGS} --orchestration=k8s --pool-mode=cluster --namespace-mode=${NAMESPACE_MODE} --exclude-tags=${EXCLUDE_TAGS};
-      if [ $(cat $HOME/test_results/${SESSION}-cluster/${SESSION}-cluster-sessionresult.json | jq -r '.result') != "pass" ]; then exit 1; fi 
+      if [ $(cat $HOME/test_results/${SESSION}-cluster/${SESSION}-cluster-sessionresult.json | jq -r '.result') != "pass" ]; then echo "Smoke test failed"; exit 1; fi 
 
 K8s-Nodeport-Mode:
   tags: 
@@ -119,6 +117,6 @@ K8s-Nodeport-Mode:
       SESSION=$(echo $BUILD_IMG_TAG | awk -F ':' '{print $2}')
       sed -i  "/bigip_controller_img/c\    \"bigip_controller_img\": \"${BUILD_IMG_TAG}\"," ~/testenv_symbols/testenv_symbols.json
       cd $HOME/${TEST_DIR} && scripts/run_systests.sh   --project=bigip_ctlr --session=${SESSION}-nodeport --include-tags=${INCLUDE_TAGS} --orchestration=k8s --pool-mode=nodeport --namespace-mode=${NAMESPACE_MODE} --exclude-tags=${EXCLUDE_TAGS} ;
-      if [ $(cat $HOME/test_results/${SESSION}-cluster/${SESSION}-nodeport-sessionresult.json | jq -r '.result') != "pass" ]; then exit 1; fi 
+      if [ $(cat $HOME/test_results/${SESSION}-cluster/${SESSION}-nodeport-sessionresult.json | jq -r '.result') != "pass" ]; then echo "Smoke test failed"; exit 1; fi 
 
 
